# Node address.
ip = "127.0.0.1"

# Node port.
port = "3413"

# Node protocol. Either HTTP or HTTPS.
proto = "http"

# API username. Comment out if user is not required.
user = "grin"

# API secret path. Comment out if secret is not required.
api_secret_path = "~/.grin/main/.api_secret"

# Foreign API secret path. Comment out if secret is not required.
foreign_api_secret_path = "~/.grin/main/.foreign_api_secret"

# Path to Grin directory.
grin_dir = "~/.grin"

# Enable or disable CoinGecko API.
coingecko_api = "enabled"

# Enable or disable node POST API public access.
public_api = "enabled"


# Grinnode config
# ip = "grinnode.live"
# port = "3413"
# proto = "https"
# coingecko_api = "enabled"
# public_api = "enabled"


# Grincoin config
# ip = "grincoin.org"
# proto = "https"
# coingecko_api = "enabled"
# public_api = "enabled"


# Testnet config
# ip = "127.0.0.1"
# port = "13413"
# proto = "http"
# user = "grin"
# api_secret_path = "~/.grin/test/.api_secret"
# foreign_api_secret_path = "~/.grin/test/.foreign_api_secret"
# grin_dir = "~/.grin"
# coingecko_api = "disabled"
# public_api = "enabled"

