[default]
address = "127.0.0.1"

# Uncomment and change default port number (8000) if another instance of the explorer is needed to run.
# E.g. Mainnet (8000) and Testnet (8001) instances.
# port = 8000

[default.databases.sqlite_db]
url = "database.sqlite"

